---
version: '3'
services:
  proxy:
    image: nginx:1-alpine
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    expose:
      - 12345
    ports:
      - 12345:12345
    depends_on:
      - tester1
      - tester2
  tester1:
    image: katacoda/docker-http-server
    hostname: paco1
  tester2:
    image: katacoda/docker-http-server
    hostname: paco2
